### ISSUE TITLE
is it possible to use the video library ?

### ISSUE THREAD

**Issue by bablukid** [andyli/hxProcessing#1]
Hi Andy,
thanks for this very usefull guide !! :)

I'm currently trying to use the video package.
I copied the "extra libraries" jars (video,serial,net...) in my project.
It compiles fine, but at runtime, I get a JNA error : 

cmd: java -jar bin/Spirolux.jar
Exception in thread "Animation Thread" java.lang.UnsatisfiedLinkError: can't load library gio-2.0 (gio-2.0|libgio-2.0|libgio-2.0-0) with -Djna.library.path=C:/projects/hxProcessing/bin/lib/. Last error:java.lang.UnsatisfiedLinkError: Unable to load library 'gio-2.0': Le module spécifié est introuvable.

```
at processing.video.LibraryLoader.loadLibrary(Unknown Source)
at processing.video.LibraryLoader.load(Unknown Source)
at processing.video.LibraryLoader.preLoadLibs(Unknown Source)
at processing.video.LibraryLoader.getInstance(Unknown Source)
at processing.video.Video.initImpl(Unknown Source)
at processing.video.Video.init(Unknown Source)
at processing.video.Capture.initGStreamer(Unknown Source)
at processing.video.Capture.<init>(Unknown Source)
at haxe.root.Spirolux.setup(Unknown Source)
at processing.core.PApplet.handleDraw(PApplet.java:2361)
at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
at processing.core.PApplet.run(PApplet.java:2256)
at java.lang.Thread.run(Unknown Source)
```

the dlls are there (i'm on Win7) since I copied the whole lib directory from processing, but it seems there is a path issue or something like that.

any idea ??

**Comment by andyli** [comment]
It is possible to use the video lib. I have just tested and it works. Check the following:
- You're running the jar with a 32bit jre, just because the processing video lib is 32bit. You may check it by `java -version`. The 64bit one will print a version mentioning "64-Bit". If there is no such string, it should be 32bit.
- Copy the contents of `processing-2.2.1\modes\java\libraries\video\library\windows32` into the `lib` folder of the haxe output folder, such that after haxe compilation, the `lib` folder will contains:
  - core.jar, jna.jar, video.jar, and other jar files
  - libgio-2.0-0.dll, and other dll files
  - a folder named `plugins`, in which there are even more dlls

**Comment by bablukid** [comment]
it works, thank you so much !  I'm very excited to use Haxe for processing !
